[package]
name = "patcher-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
thl-patcher = { version = "0.1.0", path = "../patcher-lib" }
tar = "0.4.44"
xz2 = "0.1.7"
clap = { version = "4.5.50", features = ["derive"] }
anyhow = "1.0.100"
