[package]
name = "patch-creator"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.0", features = ["wgpu"] }
rfd = "0.15.4"
thl-patcher = { version = "0.1.0", path = "../patcher-lib", default-features = false, features = ["diff"] }
tar = "0.4.44"
xz2 = "0.1.7"
